spring.application.name=appTrip

spring.datasource.url=jdbc:mysql://localhost:3306/apptrip?serverTimezone=America/El_Salvador
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true